### ISSUE TITLE
ToDo's for the documentation

### ISSUE THREAD

**Issue by uvchik** [oemof/demandlib#48]
* [ ] Add a paragraph about the limitations of the standardised load profiles
* [ ] Fill [usage](https://demandlib.readthedocs.io/en/features-revise-methods-for-elec-slp/bdew.html#usage) section of the BDEW heat profiles
* [x] Add details for the types of electrical profiles -> PR #44 
* [ ] ...

Please add ToDo's for the documentation here.

**Comment by maurerle** [comment]
It would be very helpful to also provide some of the content here:
https://github.com/oemof/demandlib/blob/dev/examples/electricity_demand_example.py
on the readthedocs page :)

Furthermore the content in the examples file seems to be outdated as there is no profile for `i0, i1, i2`
https://github.com/oemof/demandlib/blob/5cb5784eb3d35e666c01d801ff25404ee1dc27f7/examples/electricity_demand_example.py#L52-L54

The documentation states, that g7 is also available, but I do not get data when requesting G7 as a loadprofile :)
